### ISSUE TITLE
http://semver.io/node.json claims 0.12.4 to be unstable

### ISSUE THREAD

**Issue by mzgol** [heroku/semver.io#35]
Node.js 0.12.4 is the latest patch release for Node.js 0.12, it's not unstable and yet http://semver.io/node.json shows it as such, claiming latest stable version is 0.12.3.

Why is that?

**Comment by hunterloftis** [comment]
@mzgol unstable will always show the latest release, while stable is limited by the env var `MAX_STABLE_NODE`. (this is for cases where a nominally stable release ends up breaking major functionality, like 0.10.34).

Since testing stable versions and bumping the env var is a manual process, I usually lag behind the latest patch version.

**Comment by mzgol** [comment]
Thx, good to know.

**Comment by mzgol** [comment]
I'll close this issue since there's nothing to do here.
