### ISSUE TITLE
NodeJS Version on semver.io is not the latest

### ISSUE THREAD

**Issue by wytesk133** [heroku/semver.io#52]
The latest version of NodeJS is 5.1.0 but https://semver.io/node/stable says 5.0.0

**Comment by zeke** [comment]
semver.io's definition of `stable` is not always the absolute latest version of node: it's a reflection of what Heroku's team considers stable based on experience with customer apps running on the platform.

If you want to use the latest release, consider using https://semver.io/node/unstable

See https://semver.io/node.json for the full version list.

**Comment by ehd** [comment]
@zeke I can definitely follow your reasoning, but I was also surprised that resolving 5.x went to 5.0.0 instead of 5.1.1 after https://nodejs.org/en/blog/vulnerability/december-2015-security-releases/ was reported

**Comment by zeke** [comment]
I see. It looks like https://semver.io/node/stable is now `5.1.1`, but I will defer to @hunterloftis for an authoritative answer about why it was held back for a while.

**Comment by hunterloftis** [comment]
@wytesk133 @ehd You should always specify a version of node for your app; don't depend on defaults. The defaults will always be behind the latest versions because we test them before manually bumping.

Also, in the future the service will be updated to mirror the new node release pattern, with LTS/stable (4.2.3/5.1.1) instead of the old stable/unstable (0.10.41/0.11.16).

**Comment by ehd** [comment]
@zeke @hunterloftis Thanks, and I totally agree! We're pinning version now. Another idea was using `>=5.1.1 <6` or `^5.1.1`, any opinion on that? I think it could lead to undesirable binary dependency breakage. So now we've added node version upgrades to our weekly chores for that project.
